version: '3.8'
services:
  api-gateway:
    build: .
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_APPLICATION_NAME=api-gateway
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8090/eureka
    networks:
      - libmark-network

networks:
  libmark-network:
    external: true