spring.application.name=api-gateway

server.port=8080

#Config de Eureka:
eureka.client.service-url.defaultZone=http://localhost:8090/eureka/

#La visualización del registro de eureka debería quedar en false (no visible).
eureka.client.register-with-eureka=true

#La visualización del registro de eureka debería quedar en false (no visible).
eureka.client.fetch-registry=true

eureka.instance.prefer-ip-address=true


#Ruta para microservicios:
#Ruta MS User:
spring.cloud.gateway.server.webflux.routes[0].id=LMUserMS
spring.cloud.gateway.server.webflux.routes[0].uri=lb://LMUserMS
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/v1/usuarios/**,/api/v1/roles/**

#Ruta MS Customer:
spring.cloud.gateway.server.webflux.routes[1].id=LMCustomerMS
spring.cloud.gateway.server.webflux.routes[1].uri=lb://LMCustomerMS
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/v1/clientes/**,/api/v1/direcciones/**

#Ruta MS Catalog:
spring.cloud.gateway.server.webflux.routes[2].id=LMCatalogMS
spring.cloud.gateway.server.webflux.routes[2].uri=lb://LMCatalogMS
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/v1/productos/**,/api/v1/proveedores/**,/api/v2/productos/**,/api/v2/proveedores/**

#Ruta MS Order:
spring.cloud.gateway.server.webflux.routes[3].id=LMOrderMS
spring.cloud.gateway.server.webflux.routes[3].uri=lb://LMOrderMS
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/v1/pedidos/**

#Ruta MS Stock:
spring.cloud.gateway.server.webflux.routes[4].id=LMStockMS
spring.cloud.gateway.server.webflux.routes[4].uri=lb://LMStockMS
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/v1/inventarios/**,/api/v2/inventarios/**

#Ruta MS Cart:
spring.cloud.gateway.server.webflux.routes[5].id=LMCartMS
spring.cloud.gateway.server.webflux.routes[5].uri=lb://LMCartMS
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/api/v1/carritos/**

#Ruta MS Sell:
spring.cloud.gateway.server.webflux.routes[6].id=LMSellMS
spring.cloud.gateway.server.webflux.routes[6].uri=lb://LMSellMS
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/api/v1/descuentos/**,/api/v1/ventas/**

#Ruta MS Payment:
spring.cloud.gateway.server.webflux.routes[7].id=LibreriaMaketPaymentMS
spring.cloud.gateway.server.webflux.routes[7].uri=lb://LibreriaMaketPaymentMS
spring.cloud.gateway.server.webflux.routes[7].predicates[0]=Path=/api/v1/pagos/**,/api/v1/metodos-de-pago/**
#SWAGGER

# Ruta MS Stock - Swagger:
#spring.cloud.gateway.server.webflux.routes[4].id=LMStockMS-swagger
#spring.cloud.gateway.server.webflux.routes[4].uri=lb://LMStockMS
#spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/lmstockms/doc/**,/lmstockms/v1/api-docs/**
#spring.cloud.gateway.server.webflux.routes[4].filters[0]=StripPrefix=1

# Ruta MS Catalog - Swagger:
#spring.cloud.gateway.server.webflux.routes[5].id=LMCatalogMS-swagger
#spring.cloud.gateway.server.webflux.routes[5].uri=lb://LMCatalogMS
#spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/lmcatalogms/doc/**,/lmcatalogms/v3/api-docs/**
#spring.cloud.gateway.server.webflux.routes[5].filters[0]=StripPrefix=1


## ahora, se debe configurar OpenFEIGN en cada microservicio para dejar solo el nombre del servicio tal cual como lo está manejando Eureka.
# Así, OpenFEIGN buscará los MS no por ruta, sino por el nombre del MS que está registrado en Eureka.
#El nombre de cada MS es el que está indicado en application.properties de cada MS.

#CONFIGURACIÓN DE DOCUMENTACÍÓN:
#SWAGGER:
springdoc.swagger-ui.path=/swagger-ui.html

#Las siguientes dos opciones son para que busque los informes mediante Eureka
#si es que no las definimos manualmente como abajo
#springdoc.enable-native-support=true
#springdoc.swagger-ui.show-common-extensions=true


springdoc.swagger-ui.urls[0].name=LMCustomerMS
springdoc.swagger-ui.urls[0].url=/api/v1/clientes/v3/api-docs

springdoc.swagger-ui.urls[1].name=LMCartMS
springdoc.swagger-ui.urls[1].url=/api/v1/carritos/v3/api-docs

springdoc.swagger-ui.urls[2].name=LMCatalogMS
springdoc.swagger-ui.urls[2].url=/api/v1/productos/v3/api-docs

springdoc.swagger-ui.urls[3].name=LMStockMS
springdoc.swagger-ui.urls[3].url=/api/v1/inventarios/v3/api-docs

springdoc.swagger-ui.urls[4].name=LMSellMS
springdoc.swagger-ui.urls[4].url=/api/v1/ventas/v3/api-docs

springdoc.swagger-ui.urls[5].name=LibreriaMaketPaymentMS
springdoc.swagger-ui.urls[5].url=/api/v1/pagos/v3/api-docs


