spring.application.name=api-gateway

server.port=8080

#Config de Eureka:
eureka.client.service-url.defaultZone=http://localhost:8090/eureka/

#La visualización del registro de eureka debería quedar en false (no visible).
eureka.client.register-with-eureka=true

#La visualización del registro de eureka debería quedar en false (no visible).
eureka.client.fetch-registry=true

eureka.instance.prefer-ip-address=true

#La siguiente configuración permite que Gateway le indique a cada microservicio conectado de que las peticiones entran por el puerto designado a Gateway.
#Puede ser parte del problema de comunicación de los servicios dockerizados.
#Comentar las 2 líneas si da problemas con dockerización.
# 1. Conservar el Host original que usa el cliente en Postman
# Conserva el Host (localhost:8080) para que Spring HATEOAS arme bien los links
#spring.cloud.gateway.default-filters[0]=PreserveHostHeader
#spring.cloud.gateway.x-forwarded.host-enabled=true
#spring.cloud.gateway.x-forwarded.port-enabled=true

#Ruta para microservicios:
#Ruta MS User:
spring.cloud.gateway.server.webflux.routes[0].id=LMUserMS
spring.cloud.gateway.server.webflux.routes[0].uri=lb://LMUserMS
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/v1/usuarios/**,/api/v1/roles/**

#Ruta MS Customer:
spring.cloud.gateway.server.webflux.routes[1].id=LMCustomerMS
spring.cloud.gateway.server.webflux.routes[1].uri=lb://LMCustomerMS
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/v1/clientes/**,/api/v1/direcciones/**,/api/v2/clientes/**,/api/v2/direcciones/**

#Ruta MS Catalog:
spring.cloud.gateway.server.webflux.routes[2].id=LMCatalogMS
spring.cloud.gateway.server.webflux.routes[2].uri=lb://LMCatalogMS
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/v1/productos/**,/api/v1/proveedores/**,/api/v2/productos/**,/api/v2/proveedores/**

#Ruta MS Order:
spring.cloud.gateway.server.webflux.routes[3].id=LMOrderMS
spring.cloud.gateway.server.webflux.routes[3].uri=lb://LMOrderMS
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/v1/pedidos/**

#Ruta MS Stock:
spring.cloud.gateway.server.webflux.routes[4].id=LMStockMS
spring.cloud.gateway.server.webflux.routes[4].uri=lb://LMStockMS
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/v1/inventarios/**,/api/v2/inventarios/**

#Ruta MS Cart:
spring.cloud.gateway.server.webflux.routes[5].id=LMCartMS
spring.cloud.gateway.server.webflux.routes[5].uri=lb://LMCartMS
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/api/v1/carritos/**

#Ruta MS Sell (CORREGIDO MAYÚSCULAS PARA MATCH CON DOCKER):
spring.cloud.gateway.server.webflux.routes[6].id=LMSellMS
spring.cloud.gateway.server.webflux.routes[6].uri=lb://LMSELLMS
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/api/v1/descuentos/**,/api/v1/ventas/**

#Ruta MS Payment:
spring.cloud.gateway.server.webflux.routes[7].id=LibreriaMaketPaymentMS
spring.cloud.gateway.server.webflux.routes[7].uri=lb://LibreriaMaketPaymentMS
spring.cloud.gateway.server.webflux.routes[7].predicates[0]=Path=/api/v1/pagos/**,/api/v1/metodos-de-pago/**

#CONFIGURACIÓN DE DOCUMENTACIÓN SWAGGER:
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.doc-expansion=list

springdoc.swagger-ui.urls[0].name=LMCustomerMS
springdoc.swagger-ui.urls[0].url=/api/v1/clientes/v3/api-docs

springdoc.swagger-ui.urls[1].name=LMCartMS
springdoc.swagger-ui.urls[1].url=/api/v1/carritos/v3/api-docs

springdoc.swagger-ui.urls[2].name=LMCatalogMS
springdoc.swagger-ui.urls[2].url=/api/v1/productos/v3/api-docs

springdoc.swagger-ui.urls[3].name=LMStockMS
springdoc.swagger-ui.urls[3].url=/api/v1/inventarios/v3/api-docs

# URL de Ventas Corregida a v1 (hace match con el properties de Ventas)
springdoc.swagger-ui.urls[4].name=LMSellMS
springdoc.swagger-ui.urls[4].url=/api/v1/ventas/v3/api-docs

springdoc.swagger-ui.urls[5].name=LibreriaMaketPaymentMS
springdoc.swagger-ui.urls[5].url=/api/v1/pagos/v3/api-docs