spring.application.name=api-gateway

server.port=8080

#Config de Eureka:
eureka.client.service-url.defaultZone=http://localhost:8090/eureka/

#La visualización del registro de eureka debería quedar en false (no visible).
eureka.client.register-with-eureka=true

#La visualización del registro de eureka debería quedar en false (no visible).
eureka.client.fetch-registry=true

eureka.instance.prefer-ip-address=true


#Ruta para microservicios:
#Ruta MS Customer:
spring.cloud.gateway.server.webflux.routes[0].id=LMCustomerMS
spring.cloud.gateway.server.webflux.routes[0].uri=lb://LMCustomerMS
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/v1/clientes/**

#Ruta MS Catalog:
spring.cloud.gateway.server.webflux.routes[1].id=LMCatalogMS
spring.cloud.gateway.server.webflux.routes[1].uri=lb://LMCatalogMS
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/v1/productos/**

#Ruta MS Order:
spring.cloud.gateway.server.webflux.routes[2].id=LMOrderMS
spring.cloud.gateway.server.webflux.routes[2].uri=lb://LMOrderMS
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/v1/pedidos/**

## ahora, se debe configurar OpenFEIGN en cada microservicio para dejar solo el nombre del servicio tal cual como lo está manejando Eureka.
# Así, OpenFEIGN buscará los MS no por ruta, sino por el nombre del MS que está registrado en Eureka.
#El nombre de cada MS es el que está indicado en application.properties de cada MS.
